# Generated by Django 5.2 on 2025-04-28 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('mail', models.CharField(max_length=100, verbose_name='почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название блюда')),
                ('img', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(verbose_name='описание блюда')),
                ('category', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], max_length=100, verbose_name='категория')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='рецепт')),
            ],
            options={
                'verbose_name_plural': 'блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('unit', models.CharField(max_length=100, verbose_name='единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('breakfast', 'Завтраки'), ('lunch', 'Обеды'), ('dinner', 'Ужины'), ('dessert', 'Десерты')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Цена опции',
                'verbose_name_plural': 'Цены опций',
            },
        ),
        migrations.CreateModel(
            name='MealPlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(3, '3 мес'), (12, '12 мес')])),
                ('include_breakfast', models.BooleanField()),
                ('include_lunch', models.BooleanField()),
                ('include_dinner', models.BooleanField()),
                ('include_dessert', models.BooleanField()),
                ('new_year_menu', models.BooleanField()),
                ('persons', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_models.client')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_menu', to='food_models.dish', verbose_name='завтрак')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_menu', to='food_models.dish', verbose_name='ужин')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_menu', to='food_models.dish', verbose_name='обед')),
            ],
            options={
                'verbose_name': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepts', to='food_models.dish')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepts', to='food_models.ingredient')),
            ],
            options={
                'verbose_name': 'ингредиент блюда',
                'verbose_name_plural': 'ингредиенты блюд',
            },
        ),
    ]
