# Generated by Django 5.2 on 2025-04-23 21:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('mail', models.CharField(max_length=100, verbose_name='почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название блюда')),
                ('img', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(verbose_name='описание блюда')),
            ],
            options={
                'verbose_name': 'блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('unit', models.CharField(max_length=100, verbose_name='единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allergy_ingredients', to='food_models.ingredient', verbose_name='ингредиент')),
            ],
            options={
                'verbose_name': 'аллергичный ингредиент',
                'verbose_name_plural': 'аллергичные ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='food_models.allergy')),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_menu', to='food_models.dish', verbose_name='завтрак')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_menu', to='food_models.dish', verbose_name='ужин')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_menu', to='food_models.dish', verbose_name='обед')),
            ],
            options={
                'verbose_name': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_models.dish')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_models.ingredient')),
            ],
            options={
                'verbose_name': 'ингредиент блюда',
                'verbose_name_plural': 'ингредиенты блюд',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='общая стоимость')),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата регистрации')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='food_models.client', verbose_name='клиент')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_models.recept', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
