# Generated by Django 5.2 on 2025-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionprice',
            options={'verbose_name': 'Цена опции', 'verbose_name_plural': 'Цены опций'},
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='name',
        ),
        migrations.AddField(
            model_name='optionprice',
            name='option',
            field=models.CharField(choices=[('breakfast', 'Завтраки'), ('lunch', 'Обеды'), ('dinner', 'Ужины'), ('dessert', 'Десерты'), ('new_year', 'Новогоднее меню')], default='breakfast', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
